'use client';

import * as React from 'react';
import { GoogleMeetLogo } from './icons';

/**
 * Full-screen "Interview completed" state shown when the AI agent concludes
 * the interview (publishes {"type":"interview_concluded","summary"} on the
 * data channel — see interview-musetalk server.py _on_interview_concluded).
 * Replaces the whole conference UI. When `resultUrl` is provided (main-app
 * deep link built from the room name == sessionId), auto-redirects there
 * after a short countdown — the report is generated by Node's
 * finalizeInterviewSession as soon as the agent's conclude POST lands.
 */
export function InterviewCompletedScreen({
  summary,
  resultUrl,
}: {
  summary: string;
  resultUrl?: string;
}) {
  const [countdown, setCountdown] = React.useState(6);

  React.useEffect(() => {
    if (!resultUrl) return;
    const tick = setInterval(() => setCountdown((c) => c - 1), 1000);
    const redirect = setTimeout(() => window.location.replace(resultUrl), 6000);
    return () => {
      clearInterval(tick);
      clearTimeout(redirect);
    };
  }, [resultUrl]);

  return (
    <div className="ail-ended" role="status">
      <div className="ail-ended-card">
        <div className="ail-ended-mark" aria-hidden="true">
          <GoogleMeetLogo size={48} />
        </div>
        <h1 className="ail-ended-title">Interview completed</h1>
        <p className="ail-ended-msg">{summary || 'Thanks for your time. Have a great day!'}</p>
        <p
          className="ail-ended-msg"
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10 }}
        >
          <span className="ail-spinner" aria-hidden="true" />
          Calculating your report…
        </p>

        {resultUrl && (
          <div className="ail-ended-actions">
            <a className="ail-ended-btn-primary" href={resultUrl}>
              {countdown > 0 ? `View report (${countdown})` : 'View report'}
            </a>
          </div>
        )}
      </div>
    </div>
  );
}
